name: r2_gaussian
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - plyfile
  - python=3.9
  - pip=22.3.1
  - mkl==2024.0
  - numpy==1.24.1
  - tqdm
  - tensorboard
  - tensorboardX
  - pyyaml
  - pip:
    - opencv-python
    - matplotlib
    - pydicom
    - tifffile
    - imagecodecs
    - pyvista
    - SimpleITK
    - scikit-image
    - Cython==0.29.36
    - open3d==0.18.0
    - -e r2_gaussian/submodules/simple-knn
    - -e r2_gaussian/submodules/xray-gaussian-rasterization-voxelization